name: CI

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: omagnet-app:latest
        options: --entrypoint "/bin/sh -c 'sleep infinity'"

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install --with dev

    - name: Run tests
      run: |
        poetry run pytest
